<project xmlns='http://maven.apache.org/POM/4.0.0'>
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.instanto</groupId>
    <artifactId>gwt-material-widgets-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>
  <artifactId>gwt-material-widgets-assets</artifactId>
  <build>
    <plugins><plugin><groupId>io.instanto</groupId><artifactId>gwt-material-build-maven-plugin</artifactId><version>${project.version}</version><executions><execution><goals><goal>material-resources</goal></goals></execution></executions><configuration><resourceInput>${project.basedir}/../target/intake/core/gwt-material/src/main/resources</resourceInput></configuration></plugin></plugins>
    <resources>
      <resource>
        <directory>..</directory>
        <targetPath>META-INF</targetPath>
        <includes>
          <include>LICENSE</include>
          <include>NOTICE</include>
          <include>upstream/assessment-lock.json</include>
        </includes>
      </resource>
      <resource>
        <directory>${project.build.directory}/generated-resources/material/gwt/material/design/public</directory>
        <targetPath>META-INF/resources/gwt-material</targetPath>
      </resource>
      <resource>
        <directory>${project.build.directory}/generated-resources/material/gwt/material/design/client/resources/js</directory>
        <targetPath>META-INF/resources/gwt-material/js</targetPath>
      </resource>
    </resources>
  </build>
</project>
